name: yatrikaa
description: "Yatrikaa - Your Travel Companion"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1000

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  font_awesome_flutter: ^10.12.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  http_parser: ^4.0.0
  intl: ^0.19.0
  provider: ^6.1.5+1
  connectivity_plus: ^7.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_animate: 4.5.1
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  google_sign_in: ^7.2.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^21.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logoSquare.png"
  min_sdk_android: 21 # android min sdk version

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700