// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJo6yYM1EQxyA_FdB8ooiQGlQBBxV-SGY',
    appId: '1:47075741345:web:2f32e00b9526702ffa2ae0',
    messagingSenderId: '47075741345',
    projectId: 'yatrikaa-app',
    authDomain: 'yatrikaa-app.firebaseapp.com',
    storageBucket: 'yatrikaa-app.firebasestorage.app',
    measurementId: 'G-H644101CNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dy2O9R7CEHhVFdZ0iRl44VZY15tVdOo',
    appId: '1:47075741345:android:2cdac205e98cf841fa2ae0',
    messagingSenderId: '47075741345',
    projectId: 'yatrikaa-app',
    storageBucket: 'yatrikaa-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0oYGhXMhRFFBSxB77NMzHcL2larwFDE',
    appId: '1:47075741345:ios:cfab13ef36fb3902fa2ae0',
    messagingSenderId: '47075741345',
    projectId: 'yatrikaa-app',
    storageBucket: 'yatrikaa-app.firebasestorage.app',
    iosBundleId: 'com.yatrikaa.app',
  );
}
